# This workflow checks that the code snippets (manifests) are valid.
name: manifests-validation
on:
  push:
    paths:
      # workflows
      - ".github/workflows/manifests-validation.yaml"
      # script
      - ".github/workflows/parser.py"
      # documentation
      - "workloads/**/*.md"
      - "configuration/**/*.md"
      - "storage/**/*.md"
      - "access-control/**/*.md"
      - "custom-resource-definitions/**/*.md"
concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  extract-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Parse Markdown files and extract yaml snippets
      run: python .github/workflows/parser.py
    - name: List yaml snippets
      run: ls -R manifests
    - name: Store yaml snippets
      uses: actions/upload-artifact@v2
      with:
        name: manifests
        path: manifests
  
  validate-manifests:
    needs: extract-manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Install kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.4.13
      - name: Load yaml snippets
        uses: actions/download-artifact@v2
        with:
          name: manifests
          path: manifests
      - name: List yaml snippets
        run: ls -R manifests
      - name: Validate yaml snippets
        run: kubeconform manifests
